// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALDaHnnmZ8xO388_Jtmcsxnf-Z-zKct9I',
    appId: '1:223236194053:android:004a2251fb7f9a84f9816c',
    messagingSenderId: '223236194053',
    projectId: 'resresapp',
    databaseURL: 'https://resresapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resresapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFZykaTFN1_Wyk-Wm1NbIvpl8VziXwLJQ',
    appId: '1:223236194053:ios:e62553714a8d5b4cf9816c',
    messagingSenderId: '223236194053',
    projectId: 'resresapp',
    databaseURL: 'https://resresapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resresapp.appspot.com',
    androidClientId: '223236194053-g3fiuufq1b8f2uud4ksg64bi8cfc5pgt.apps.googleusercontent.com',
    iosClientId: '223236194053-n88ocra6ckcq7h9229fafaasnfmug5t4.apps.googleusercontent.com',
    iosBundleId: 'iit.heathens.reservationapp',
  );
}
